In [1]:
import pandas as pd 
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
set_1 = pd.read_csv('mean_ratings_set1.csv')
set_2 = pd.read_csv('mean_ratings_set2.csv')

In [3]:
#Removendo linhas que possuam atributo target == Happy e atributo target == Sad, pois são multiclasse

set_1 = set_1[set_1['TARGET'] != 'HAPPY']
set_2 = set_2[set_2['TARGET'] != 'HAPPY']

set_1 = set_1[set_1['TARGET'] != 'SAD']
set_2 = set_2[set_2['TARGET'] != 'SAD']

set_2 = set_2.drop(['soundtrack', 'link'], axis=1) #Possuem colunas do tipo string --> não  são necessária para o PCA



In [4]:
set_1.head()

number  valence  energy  tension  anger  fear  happy   sad  tender  TARGET
60      61     5.80    2.80      2.4    1.0   1.0   5.83  2.00    7.83  TENDER
61      62     6.83    4.33      2.5    1.0   1.0   2.20  2.80    7.60  TENDER
62      63     5.83    2.00      2.0    1.0   1.0   1.60  4.40    7.40  TENDER
63      64     6.60    2.40      1.2    1.0   1.0   4.17  1.50    7.17  TENDER
64      65     6.40    3.20      1.8    1.0   1.0   4.50  2.17    7.17  TENDER

In [5]:
set_2.head()

Number  Valence  Energy  Tension  Anger  Fear  Happy   Sad  Tender  Beauty  \
0       1     2.56    7.73     8.38   6.39  4.40   1.21  1.75    1.01    4.71   
1       2     2.50    8.21     8.56   5.76  5.93   1.09  1.60    1.10    4.57   
2       3     2.92    8.21     8.17   6.31  4.06   1.31  1.55    1.01    4.45   
3       4     2.88    6.75     7.98   5.42  4.51   1.19  2.10    1.06    4.00   
4       5     3.08    6.83     7.50   6.13  4.24   1.07  2.96    1.07    5.08   

   Liking      TARGET  
0    4.97  ANGER_HIGH  
1    4.79  ANGER_HIGH  
2    5.06  ANGER_HIGH  
3    4.35  ANGER_HIGH  
4    5.35  ANGER_HIGH

In [6]:

#Pegar os valores únicos de target --> Usando estrutura de dados SET python


targets_values_set1 = set((set_1['TARGET'].values))
targets_values_set2 = set((set_2['TARGET'].values))

targets_values = targets_values_set1 | targets_values_set2

targets_values


{'ANGER',
 'ANGER_HIGH',
 'ANGER_MODERATE',
 'ENERGY NEG HIGH',
 'ENERGY NEG MODERATE',
 'ENERGY POS HIGH',
 'ENERGY POS MODERATE',
 'FEAR',
 'FEAR_HIGH',
 'FEAR_MODERATE',
 'HAPPY_HIGH',
 'HAPPY_MODERATE',
 'HIGH ENERGY',
 'HIGH TENSION',
 'HIGH VALENCE',
 'LOW ENERGY',
 'LOW TENSION',
 'LOW VALENCE',
 'SAD_HIGH',
 'SAD_MODERATE',
 'SURPRISE',
 'TENDER',
 'TENDER_HIGH',
 'TENDER_MODERATE',
 'TENSION NEG HIGH',
 'TENSION NEG MODERATE',
 'TENSION POS HIGH',
 'TENSION POS MODERATE',
 'VALENCE NEG HIGH',
 'VALENCE NEG MODERATE',
 'VALENCE POS HIGH',
 'VALENCE POS MODERATE'}

In [7]:
#classificar os targets_values em 8 cores diferentes emm formato rgb

cor = {"AZUL":(0,0,255), "VERMELHO":(255,0,0), "VERDE":(0,255,0), "AMARELO":(255,255,0), "ROSA":(255,0,255), "LARANJA":(255,128,0), "MARROM":(128,64,0), "CINZA":(128,128,128)}


In [13]:
def Transformacao_Linear(df):
    
    y = df['TARGET']
    x = df.drop(['TARGET'], axis=1)

    #Normalizar valores em uma mesma escala
    Normalizado = StandardScaler()
    Normalizado.fit(x)
    escalonado = Normalizado.transform(x)

    #Apos normalização e escalonamento das métricas aplicar o pca
    
    num_components = 3    
    pca = PCA(n_components = num_components)    
    pca.fit(escalonado)    
    print("Autovalores: ", pca.explained_variance_ratio_, "\n\n","Autovetores: ", pca.components_, "\n\n")
    
    #transformando os dados em vetor rgb    
    
    x = pca.transform(escalonado)
    
    #print(df.head())
    
    print("\n\n\n")
    
    print(x)
    
    

In [14]:
Transformacao_Linear(set_1)

Autovalores:  [0.55067724 0.18192977 0.10974247] 

 Autovetores:  [[ 0.05268237  0.41745491 -0.29635453 -0.43407929 -0.36421196 -0.39610923
   0.23348776  0.23478297  0.3840738 ]
 [-0.18577038  0.1565413   0.46288483 -0.05702062  0.02315688 -0.13400123
   0.60972236 -0.57708131  0.01391785]
 [-0.95922914  0.01564614 -0.17155544 -0.02842804  0.08674397  0.05387808
  -0.12945561  0.03591559  0.14463466]] 






[[ 3.28714851e+00  1.71384679e+00  1.83193811e+00]
 [ 2.77887727e+00  7.51675284e-01  1.91643498e+00]
 [ 3.24229771e+00 -8.43537574e-01  2.25047442e+00]
 [ 3.45491688e+00  1.27102005e+00  1.94159600e+00]
 [ 3.22643189e+00  1.38066636e+00  1.81160730e+00]
 [ 2.94563180e+00  1.09511078e+00  1.87324358e+00]
 [ 3.14576923e+00  1.71539160e+00  1.69459120e+00]
 [ 3.05822050e+00  1.04906667e+00  1.84414377e+00]
 [ 2.12769956e+00  1.06981882e+00  1.70881111e+00]
 [ 2.25046388e+00  4.60969454e-01  1.83805090e+00]
 [ 3.31869987e+00  1.22993225e-01  1.99602859e+00]
 [ 2.60454860e+00  1.27688